name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: Test plugin
        run: |
          asdf plugin test opengrep "$GITHUB_WORKSPACE" "opengrep --version"

      - name: Test latest stable
        run: |
          latest_version=$(bin/latest-stable)
          echo "Latest version: $latest_version"
          [[ -n "$latest_version" ]] || exit 1

      - name: Test list all versions
        run: |
          versions=$(bin/list-all)
          echo "Available versions: $versions"
          [[ -n "$versions" ]] || exit 1

      - name: Test download and install specific version
        run: |
          # Test with a known good version
          test_version="1.8.3"
          asdf install opengrep $test_version
          asdf global opengrep $test_version
          opengrep --version

          # Verify the version is correctly installed
          installed_version=$(opengrep --version | head -n1)
          echo "Installed version output: $installed_version"

  test-different-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.8.3", "1.8.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: Test specific version ${{ matrix.version }}
        run: |
          asdf plugin add opengrep "$GITHUB_WORKSPACE"
          asdf install opengrep ${{ matrix.version }}
          asdf global opengrep ${{ matrix.version }}
          opengrep --version
